## Reinforement Learning (Обучение с подкредплением)

In [38]:
import gym ## Библиотека, содержащая игры
import numpy as np

Создадим среду игры "Frozen Lake":

In [39]:
env = gym.make("FrozenLake-v0")

#### Создание алгоритма нашей игры:

Сгенерируем таблицу "действий и состояний" игры, заполнив ее нулями:

In [40]:
Q = np.zeros([env.observation_space.n, env.action_space.n])
## Так как в игре Froze Lake 4 действия (влево, вправо, вверх, вниз), а количество состояний модели равно 16 (это взято из таблицы),
## и у библиотеки "gym" есть функции именно для этого( observ = 16, act = 4)

Зададим гиперпараметры:

In [73]:
Lr = 0.8 ## Learning Rate
y = .95 ## это гамма из уравнения Беллмана
num_episodes = 2000## Количество сыгранных игр моделью 

Создадим список наград, полученных моделью:
    

In [74]:
rList = []

Создадим сам алгоритм обучения:

In [82]:

for i in range(num_episodes):# от 0 до 20000
    ## Сначала расписываем изначальные и обнуленные данные:
    s = env.reset() ## Обнуляем первоначальное состояние
    rAll = 0 ## Обнуляем награды
    d = False ## Означает, что игра не пройдена
    j = 0 ## Обнуляем выполненные шаги
    ## Создадим цикл шагов:
    while j < 99:
        ## Совершение шага:
        j += 1 
        ## Выполнение действия:
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1))) ##argmax дает максимальное вознаграджение, второе - добавление шума
        ## Создадим функцию возвращения переменных:
        s1,r,d,_ = env.step(a) ## Мы даем функции значение шага, который она должна выпонить, вернув значения s1(новое состояние), награду за действие(равна 1 в Frozen Lake)(r), пройдена ли игра (d)
        ## Обновляем нашу таблицу урванением Беллмана:
        Q[s,a] = Q[s,a] + Lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        ## Обновляем количество наград:
        rAll += r
        ## Обновляем состояние:
        s = s1
        ## Проверяем, дошли ли мы до конца:
        if d == True:
            break
        ## Добавим наши награды в созданный ранее список rList:
        rList.append(rAll)

Оценим наш алгоритм на предмет того, как он играл:

In [83]:
print("Score over time: " + str(sum(rList) / num_episodes)) ## Средняя награда за игру

Score over time: 0.0


In [84]:
print("Final Q-Tab Score: ")
print(Q)

Final Q-Tab Score: 
[[2.01985725e-01 2.02704250e-02 2.21917781e-02 2.44543204e-02]
 [3.14103032e-03 6.98045628e-03 8.34298061e-03 9.80248843e-02]
 [9.61617535e-03 5.99370060e-03 7.78665018e-03 8.35560737e-02]
 [1.48095512e-03 1.45789094e-03 6.07319903e-04 5.26545033e-02]
 [1.86426621e-01 1.12923522e-02 9.43457046e-03 1.89233026e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.62600804e-02 6.08789634e-04 1.51176791e-04 1.04549832e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.11333399e-03 4.26028463e-03 4.90231246e-04 4.16680117e-01]
 [4.02290038e-05 6.00662761e-01 0.00000000e+00 2.93976104e-04]
 [8.81096388e-01 1.21085876e-03 1.13189331e-03 4.92150795e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.45840732e-02 8.28588684e-01 2.34297343e-02]
 [0.00000000e+00 9.97162352e-01 0.00000000e+00 4.67554295e-03]
 [0.00000000e+00 0.00000000e+00 0.0

In [85]:
print(s1)

15
