In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression


Импортируем датасет, с которым будем работать:

In [48]:
df = pd.read_csv("hw2.csv")
df

Unnamed: 0          X             Y
0             0  52.283138 -39403.717469
1             1  47.721231 -38805.816488
2             2  50.798843 -34070.976995
3             3  52.392715 -34105.400403
4             4  55.959325 -32684.917373
..          ...        ...           ...
170         170  53.063470 -38574.573150
171         171  78.847267 -60846.052662
172         172  64.999595 -54791.074223
173         173  89.794740 -64946.131356
174         174  45.435803 -28406.067850

[175 rows x 3 columns]

Обозначим X и Y:

In [ ]:
X = np.array(df["X"])
y = np.array(df["Y"])


Импортируем модель линейной регрессии из библиотеки "sklearn":

In [210]:
from sklearn import linear_model

Дадим значение переменной для модели линейной регрессии и поменяем размермность наших данных для работы:

In [ ]:
reg = linear_model.LinearRegression() 
reg
Z = X.reshape(-1, 1) 
B = y.reshape(-1, 1) 

Обучим нашу модель:

In [212]:
reg.fit(Z, B)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [213]:
reg.coef_

array([[-738.56962042]])

In [214]:
reg.score(Z, B)

0.7788864088522969

Предскажем результаты при помощи модели:

In [215]:
reg.predict(B)

array([[29104595.24960008],
       [28663003.74839393],
       [25165995.14165525],
       [25191419.22478426],
       [24142293.61293992],
       [18334306.7020246 ],
       [25701666.93717895],
       [12915859.07198934],
       [13510991.47160125],
       [26982103.98757502],
       [26394409.00807771],
       [32938200.35849621],
       [28535785.19129348],
       [22532488.22096471],
       [44712092.3400601 ],
       [38066769.2303691 ],
       [52287885.64636934],
       [24810906.65312219],
       [26794261.97556971],
       [16291110.99172807],
       [17797808.39417102],
       [24777606.23049424],
       [21270481.73243672],
       [31801828.25621774],
       [33792688.07638901],
       [29547978.24355673],
       [38001069.20115438],
       [15867282.81125029],
       [22108373.46993694],
       [35238026.35252103],
       [30016125.65727238],
       [19404597.05920365],
       [29464886.32374887],
       [24047579.88610797],
       [48011508.23183746],
       [23762037.979

In [216]:
reg.predict(Z)

array([[-36408.14207017],
       [-33038.85614785],
       [-35311.88727157],
       [-36489.07239323],
       [-39123.26217719],
       [-34445.29732727],
       [-38802.35532002],
       [-28820.0241027 ],
       [-25870.6377456 ],
       [-40087.54124288],
       [-31395.57319659],
       [-36820.33168726],
       [-36014.59553604],
       [-27669.7297647 ],
       [-53983.42137475],
       [-52411.57220379],
       [-63459.38558317],
       [-30432.19165063],
       [-31698.81828522],
       [-29455.11757258],
       [-24774.59921525],
       [-31226.43538526],
       [-38265.27696422],
       [-31646.26961278],
       [-50028.5242579 ],
       [-34565.2689755 ],
       [-48504.15398003],
       [-26872.47960128],
       [-36967.47386746],
       [-39333.74864953],
       [-43436.9687252 ],
       [-31785.30229471],
       [-38383.7266687 ],
       [-36006.66483687],
       [-64005.96312677],
       [-35012.76840657],
       [-35124.10876413],
       [-35026.86332045],
       [-269

In [217]:
reg.intercept_

array([2206.59501132])

Можно сделать вывод, что модель предсказала данные близко к исходным только по столбцу "Y" ("Z")